# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: true
cran: http://cran.rstudio.com

r_packages:
    - testthat
    - Rcpp

before_install:
    # Install TileDB
    - git clone https://github.com/TileDB-Inc/TileDB /tmp/TileDB
    - pushd /tmp/TileDB
    - git checkout dev
    - mkdir build
    - pushd build
    - ../bootstrap --enable-verbose
    - make -j 4
    - sudo make -C tiledb install
    - popd
    - popd

script:
    - R CMD BUILD .
    - R CMD check *tar.gz --install-args=--configure-args="--with-tiledb=/tmp/TileDB/dist"
